// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func SessionGenerator() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"overlay\"><div id=\"popup\" class=\"popup\"><h2>Generate a Session Token</h2><form hx-post=\"/admin/generate\" hx-target=\"#popup\"><input name=\"firstname\" type=\"text\" placeholder=\"Candidate&#39;s first name\"> <input name=\"lastname\" type=\"text\" placeholder=\"Candidate&#39;s last name\"> <input name=\"timelimit\" type=\"number\" placeholder=\"Time limit\" value=\"30\"> <label for=\"repo\">Choose a Repository:</label> <select id=\"repo\" name=\"repo\"><option value=\"sbraitsch/gourd_example\">sbraitsch/gourd_example</option> <option value=\"someother/example\">someother/example</option></select> <button class=\"submit-btn\" type=\"submit\">Generate</button></form></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
